### PR TITLE
Fix for issue #4, some small fixes, initial documentation, dev env, etc

### PR DESCRIPTION
**Pull request by ayavilevich**
Hey @MoT3rror please take a look and lmk if there are any comments.

### CODE REVIEW

**Comment by MoT3rror** [comment]
The `composer.lock` looks like it just added Sail. Did you add packages for npm? Seems like a large lock file change for no changes to `package.json`.

**Comment by ayavilevich** [comment]
you are correct about composer. 

regarding npm, I think I have a different version of node/npm than you. see ``lockfileVersion`` attribute.

https://stackoverflow.com/questions/64813775/is-there-any-way-to-fix-package-lock-json-lockfileversion-so-npm-uses-a-specific/64820435

In the container I have:

```
sail@cb73b6f23084:/var/www/html$ npm -v
7.3.0
sail@cb73b6f23084:/var/www/html$ node -v
v15.5.1
```

in WSL I have:

```
~/egginc-coop-tracker$ npm -v
bash: /mnt/c/Program Files/nodejs/npm: /bin/sh^M: bad interpreter: No such file or directory
~/egginc-coop-tracker$ node -v
v10.19.0
```

in Windows I have

```
> npm -v
6.13.7
> node -v
v12.16.1
```

https://docs.npmjs.com/cli/v6
So version 7 seems to be the "Dev" version. 6 is "Stable".

LMK what you prefer to do?
I can continue as is, just not commit this file to the repo.
You can upgrade to latest dev version of npm/node.
I can downgrade to latest stable version of npm, v6, so that it uses lockfileVersion=1

**Comment by ayavilevich** [comment]
or maybe we don't need to do anything and it will just work because they made it backward compatible:

https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major

> package-lock.json is updated to a newer format, using "lockfileVersion": 2. This format is backwards-compatible with npm CLI versions using "lockfileVersion": 1, but older npm clients will print a warning about the version mismatch.

**Comment by MoT3rror** [comment]
Not a problem. I don't think anyone has tried out NPM 7 yet in our company so it has surprised me.

**Comment by MoT3rror** [comment]
This live on the server now.

**Pull request merged**
